name: Style-check

on:
  push:
    paths:
      - '**.py'
    
jobs:

  style-check:
    runs-on: ubuntu-latest
    name: Code Style Check
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: flake8-black
        uses: py-actions/flake8@v2
        with:
          path: "."
          plugins: "flake8-black"
      - uses: isort/isort-action@v1
        with:
            requirements-files: "requirements.txt"